[phases.setup]
# Railway automatically installs python when requirements.txt is present.
# We just append nodejs to the environment so we can build the frontend.
nixPkgs = ["...", "nodejs_20"]

[phases.build]
# Use "..." to retain any default python actions, then perform node compilation
cmds = ["...", "cd frontend-react && npm install && npm run build"]
